### PR TITLE
Enums in seperate file and for pokemon names

### PR DESCRIPTION
**Pull request by jodoglevy**

### CODE REVIEW

**Comment by jodoglevy** [comment]
Btw why'd you change this within tile? isn't is an s2 cell?

-  uint64 s2cell_token = 1;
 +  uint64 id = 1;

**Comment by bettse** [comment]
Its the cell's id, not its "token".  The token is a hex string, the id is a number.

**Comment by bettse** [comment]
the content looks good, but how about putting it into holoholo_shared.proto ?

**Comment by jodoglevy** [comment]
hmm ok so you can find a region via the s2 token or s2 id?

**Comment by jodoglevy** [comment]
i could put it in there, but why? what's with the holo holo filename?

**Pull request closed without merging**
