### PR TITLE
Updating get map data API protobuf schema

### PR DESCRIPTION
**Pull request by jodoglevy**

### CODE REVIEW

**Comment by bettse** [comment]
Thanks!  I usually use less verbose names, but I'll make those tweaks after merging.

**Comment by jodoglevy** [comment]
Are we sure we want less verbose names? Harder to tell what the fields mean then isn't it?

**Comment by bettse** [comment]
A bit of it is my rubyist background, but also I think something like `unique_id_of_this_pokemon` is a bit redundant when it's nested in a Pokemon structure, and could be `uid`.  

But, as they say, naming is one of the 2 biggest problems in software engineering, along with cache invalidation and off by one errors.

**Comment by jodoglevy** [comment]
Up to you. But if we make the names less descriptive lets add comments
around the less descriptive names so at least the proto files can be used
as docs :)

**Pull request merged**
